language: node_js

node_js:
  - "0.10"
  - 0.11

branches:
  only:
    - master
    - wip

before_script:
  - npm install -g grunt-cli

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 0.11
